Version: '2.9'
checkupdate: true
Radius: 3
FluidsProtect: true
CheckItemId: 38
EnabledFor:
  TNT: true
  Cannons: false
  Creepers: false
  Ghasts: false
  Withers: false
Durability:
  Enabled: false
  Obsidian: 1
  EnchantmentTable: 1
  EnderChest: 1
  Anvil: 1
  ResetEnabled: true
  ResetAfter: '600000'
Blocks:
  ChanceToDrop: 0.7