Version: '2.8'
autoupdate: true
Radius: 3
FluidsProtect: true
EnabledFor:
  TNT: true
  Cannons: false
  Creepers: false
  Ghasts: false
  Withers: false
Durability:
  Enabled: false
  Amount: 1
  ResetEnabled: true
  ResetAfter: '600000'
EnchantmentTableDurability:
  Enabled: false
  Amount: 1
Blocks:
  ChanceToDrop: 0.7
UseFactions: false
